In [1]:
import copy
import numpy as np
import pandas as pd

In [2]:
def triangular(entrada):
	saida = [None for x in range(len(entrada))]
	for i in reversed(range(0,len(entrada[0])-1)): #for (int i=sizeof(entrada)/sizeof(entrada[0]); i > 0; i--)
		soma = 0
		for j in reversed(range(i,len(entrada))):
			if i != j: #se não for o elemento pivô
				soma += saida[j]*entrada[i][j] #calcula e coloca tudo na variavel soma pra subtrair depois
			else: # se não for elemento pivô, calcula o x( faz a regressão )
				saida[i]=(entrada[i][len(entrada[0])-1]-soma)/entrada[i][i] #subtrai soma
				break
	return saida

#Exercício 2
def escalonamento(entrada):
	n = len(entrada) # calculando o n (numero de variaveis e equacoes)
	anterior = copy.deepcopy(entrada) # usando o deepcopy para fazer a cópia do vetor
	proximo = copy.deepcopy(entrada)
	for k in range(1,n): #k iterações de 2 em diante (1, por conta do índice começar com 0)
		if proximo[k][k] == 0: #caso em que o pivô é nulo.
			return None #implementar tratamento (troca de linha)
		anterior = copy.deepcopy(proximo)
		for i in range(n): # percorrendo linhas
			for j in range(n+1): # e as colunas (n+1 por conta do `b` da matriz aumentada)
				if i < k: # aplicando o algoritmo
					proximo[i][j] = anterior[i][j]
				elif i > k-1 and j < k:
					proximo[i][j] = 0
				else:
					proximo[i][j] = anterior[i][j]-(anterior[i][k-1]/anterior[k-1][k-1]*anterior[k-1][j])
	return proximo #pronto, transformou em matriz triangular superior equivalente à matriz aumentada do início

#Exercício 3
def gauss(entrada):
	return triangular(escalonamento(entrada))

In [3]:
a = np.array([[80.0, 0.0, 30.0, 10.0],
             [0.0, 80.0, 10.0, 10.0],
             [16.0, 20.0, 60.0, 72.0],
             [4.0, 0.0, 0.0, 8.0]])

b = np.array([40.0, 27.0, 31.0, 2.0])

In [4]:
def triang_sup(a, b):
    n = np.size(b)
    for k in range(n-1):
        print('Iteração', k+1)
        for i in range(k+1, n):
            m = a[i, k]/a[k, k]

            a[i,:] = a[i,:] - (m*a[k,:])

            b[i] = b[i] - (m*b[k])

            print('Passo:', i-k)
            print("A:\n",a,"\n", "B:\n",b)
    
    return pd.DataFrame(a, b)

triang_sup(a, b)

Iteração 1
Passo: 1
A:
 [[80.  0. 30. 10.]
 [ 0. 80. 10. 10.]
 [16. 20. 60. 72.]
 [ 4.  0.  0.  8.]] 
 B:
 [40. 27. 31.  2.]
Passo: 2
A:
 [[80.  0. 30. 10.]
 [ 0. 80. 10. 10.]
 [ 0. 20. 54. 70.]
 [ 4.  0.  0.  8.]] 
 B:
 [40. 27. 23.  2.]
Passo: 3
A:
 [[80.   0.  30.  10. ]
 [ 0.  80.  10.  10. ]
 [ 0.  20.  54.  70. ]
 [ 0.   0.  -1.5  7.5]] 
 B:
 [40. 27. 23.  0.]
Iteração 2
Passo: 1
A:
 [[80.   0.  30.  10. ]
 [ 0.  80.  10.  10. ]
 [ 0.   0.  51.5 67.5]
 [ 0.   0.  -1.5  7.5]] 
 B:
 [40.   27.   16.25  0.  ]
Passo: 2
A:
 [[80.   0.  30.  10. ]
 [ 0.  80.  10.  10. ]
 [ 0.   0.  51.5 67.5]
 [ 0.   0.  -1.5  7.5]] 
 B:
 [40.   27.   16.25  0.  ]
Iteração 3
Passo: 1
A:
 [[80.          0.         30.         10.        ]
 [ 0.         80.         10.         10.        ]
 [ 0.          0.         51.5        67.5       ]
 [ 0.          0.          0.          9.46601942]] 
 B:
 [40.         27.         16.25        0.47330097]


0     1     2          3
40.000000  80.0   0.0  30.0  10.000000
27.000000   0.0  80.0  10.0  10.000000
16.250000   0.0   0.0  51.5  67.500000
0.473301    0.0   0.0   0.0   9.466019