In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\RRodr\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
#  Array a partir de uma lista
quantidade = [2, 5, 10, 20, 35]
custo = [100, 150, 450, 320, 195]

In [5]:
arr1 = np.array(quantidade)
arr2 = np.array(custo)

In [6]:
arr1

array([ 2,  5, 10, 20, 35])

In [7]:
arr2

array([100, 150, 450, 320, 195])

In [8]:
estoque = arr1*arr2

In [9]:
estoque

array([ 200,  750, 4500, 6400, 6825])

In [10]:
custo = [100, 200, 300, 400]
venda = [125, 235, 355, 490]

In [11]:
arr3 = np.array(custo)

In [12]:
arr4 = np. array(venda)

In [13]:
lucro = arr4 - arr3

In [14]:
lucro

array([25, 35, 55, 90])

In [15]:
# Arrays a partir do numpy

In [16]:
# arange()

In [17]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10, 21, 2)

array([10, 12, 14, 16, 18, 20])

In [19]:
np.arange(10, 100, 2, dtype=float)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60.,
       62., 64., 66., 68., 70., 72., 74., 76., 78., 80., 82., 84., 86.,
       88., 90., 92., 94., 96., 98.])

In [20]:
# linspace()

In [21]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# ramdom . rand, randn, randint

In [24]:
np.random.rand(10)

array([0.61509732, 0.5486961 , 0.28207869, 0.38715975, 0.12297067,
       0.35686492, 0.69642608, 0.41166037, 0.45860699, 0.04205913])

In [25]:
np.random.randn(15)

array([-1.45769191, -0.4347133 , -0.74005623,  0.3630077 , -0.69705472,
       -1.6071942 ,  0.58100899, -0.02489186, -1.05727327, -0.42716598,
        0.02869165, -0.25745848,  0.37108638,  2.27282391, -1.20574206])

In [27]:
arr = np.random.randint(10, 100, 30)

In [28]:
len(arr)

30

In [29]:
#Zeros e uns

In [30]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
# Criar array unidimensional

In [36]:
arr = np.arange(1, 11, dtype=int)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Indexação de arrays unidimensionais

In [39]:
arr[4]

5

In [40]:
arr[2:4]

array([3, 4])

In [41]:
arr[2:5]

array([3, 4, 5])

In [42]:
arr[:5]

array([1, 2, 3, 4, 5])

In [43]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#Indexação de arryas bidimensionais

In [46]:
arr2 = np.random.randint(10, 50, size=(3, 3))

In [47]:
arr2

array([[41, 33, 47],
       [37, 15, 48],
       [30, 34, 17]])

In [49]:
arr2[1][1]

15

In [50]:
arr2[1][2]

48

In [51]:
arr2[2][0:2]

array([30, 34])

In [52]:
arr3 = np.random.randint(1, 101, size=(10, 10))

In [53]:
arr3

array([[18, 77, 46, 46, 66, 96, 48, 64, 11,  7],
       [55, 77, 33, 79, 84, 17, 59, 31, 96, 91],
       [49, 44, 31, 33, 91,  8, 15, 82, 86, 51],
       [52, 36, 97, 82, 90, 60, 92, 74, 80, 92],
       [62, 70, 47, 25, 77, 11, 96, 43, 65, 50],
       [75, 58, 19, 21, 35, 96, 72, 49, 43, 61],
       [47, 97, 60, 57, 89,  3, 26, 66, 72, 90],
       [65, 73, 67, 13, 10, 30, 38, 46, 71, 19],
       [90, 28, 98, 52, 41, 75, 77, 55,  9, 87],
       [67, 72,  1, 12, 14, 53, 16, 66, 10, 81]])

In [54]:
arr3[3, 3]

82

In [55]:
arr3[0:3,7:]

array([[64, 11,  7],
       [31, 96, 91],
       [82, 86, 51]])

In [ ]:
arr3